name: Release

on:
  push:
    tags:
      - "v([0-9]+\.[0-9]+\.[0-9]+)(?:(?:(a|b|c|rc))(?:[0-9]+))?$"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup-env
      - name: Get the version from pyproject.toml
        id: pyproject
        run: echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT
      - name: Fail if pyproject.toml version is different from tag
        if: github.ref_name != format('v{0}', steps.pyproject.outputs.version)
        run: |
          echo "pyproject.toml version and tag mismatch"
          exit 1
      - name: build wheel
        run: poetry build --format wheel
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: "dist/test_github_actions*.whl"