name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup-env
      - name: Check project version
        run: make TAG=${{ github.ref_name }} check_tag_version
      - name: build wheel
        run: poetry build --format wheel
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref_name }}
          artifacts: "dist/test_github_actions*.whl"