name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+(?:a|b|rc)[0-9]+"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup-env
      - name: Get the new tag
        id: current_tag
        run: echo "version=$(poetry version --short)" >> $GITHUB_OUTPUT
      - name: test version
        run: echo ${{ steps.current_tag.outputs.version }}
      - name: test tag
        run: echo ${{ github.ref_name }}
      - name: Fail if project version is different from tag
        if: !contains(github.ref_name, steps.current_tag.outputs.version)
        run: |
          echo "pyproject.toml version and tag mismatch"
          exit 1