name: Create Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
          - next-phase

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
            echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
            exit 1
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: ./.github/actions/setup-env
      - name: Bump version
        if: github.event.inputs.version != 'next-phase'
        run: |
          echo "VERSION=$(poetry version --short ${{ github.event.inputs.version }})" >> $GITHUB_ENV
      - name: Next phase
        if:  env.VERSION == ''
        run: |
          echo "VERSION=$(poetry version --short prerelease --next-phase)" >> $GITHUB_ENV
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ env.VERSION }}
          delete-branch: true
          title: "Release: ${{ env.VERSION }} Pull Request"
          body: "This pull request contains the updated `pyproject.toml` with the new release version. Add release notes."
          base: main