name: Update version and create Release's PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
          - prerelease

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: ./.github/actions/setup-env
      - name: Install dependencies
        run: poetry install
      - name: Bump version
        id: bump_version
        run: |
          echo "version=$(poetry version ${{ github.event.inputs.version }})" >> $GITHUB_OUTPUT
      - name: Update Changelog
        id: update_changelog
        run: |
          sed -i "s/Unreleased/${{ steps.update_version.outputs.version }}/g" CHANGELOG.md
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
          body: "This pull request contains the updated pyproject.toml with the new release version"
          base: main