name: Update version and create Release's PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      prerelease_next_phase:
        description: "Next phase of prerelease"
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: ./.github/actions/setup-env
      - name: Install dependencies
        run: poetry install
      - name: Bump version
        if: github.event.inputs.prerelease_next_phase
        run: |
          echo "VERSION=$(poetry version --short ${{ github.event.inputs.version }})" >> $GITHUB_ENV
      - name: Next phase
        if: ${{ ! github.event.inputs.prerelease_next_phase }}
        run: |
          echo "VERSION=$(poetry version --short prerelease --next-phase)" >> $GITHUB_ENV
      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ env.VERSION }}
          title: "Release: ${{ env.VERSION }} Pull Request"
          body: "This pull request contains the updated `pyproject.toml` with the new release version. Add release notes."
          base: main